# Generated by Django 4.2 on 2025-10-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='longitude',
        ),
    ]
